AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudOps Assistant – Day 2 Plan History & Comparison

Globals:
  Function:
    Tags:
      Service: cloudops-assistant
      Project: CloudOpsAssistant
      Environment: prod
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type,authorization'"
      AllowOrigin: "'http://localhost:3000'"  # Restrict to local development

Resources:
  # Day 1 - Repository Scanner Function
  RepoScannerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: repo_scanner.lambda_handler
      Runtime: python3.11
      CodeUri: backend/lambda/
      MemorySize: 512
      Timeout: 60
      Tags:
        Service: cloudops-assistant
        Feature: repo-scanning
      Events:
        Api:
          Type: Api
          Properties:
            Path: /scan-repos
            Method: POST
        ApiOptions:
          Type: Api
          Properties:
            Path: /scan-repos
            Method: OPTIONS

  # Day 1 - Plan Processor Function
  PlanProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: plan_processor.lambda_handler
      Runtime: python3.11
      CodeUri: backend/lambda/
      MemorySize: 512
      Timeout: 60
      Tags:
        Service: cloudops-assistant
        Feature: plan-processing
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TerraformPlansTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /upload-plan
            Method: POST
        ApiOptions:
          Type: Api
          Properties:
            Path: /upload-plan
            Method: OPTIONS

  # Day 2 - Plan History Function
  PlanHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: plan_history.lambda_handler
      Runtime: python3.11
      CodeUri: backend/lambda/
      MemorySize: 256
      Timeout: 30
      Tags:
        Service: cloudops-assistant
        Feature: plan-history
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TerraformPlansTable
      Events:
        HistoryApi:
          Type: Api
          Properties:
            Path: /plan-history/{repo}
            Method: GET
        CompareApi:
          Type: Api
          Properties:
            Path: /compare-plans/{plan1}/{plan2}
            Method: GET
        PlanDetailsApi:
          Type: Api
          Properties:
            Path: /plan-details/{plan_id}
            Method: GET
        HistoryOptions:
          Type: Api
          Properties:
            Path: /plan-history/{repo}
            Method: OPTIONS
        CompareOptions:
          Type: Api
          Properties:
            Path: /compare-plans/{plan1}/{plan2}
            Method: OPTIONS
        PlanDetailsOptions:
          Type: Api
          Properties:
            Path: /plan-details/{plan_id}
            Method: OPTIONS

  # Day 2 - Terraform Plans Table for history tracking
  TerraformPlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: terraform-plans
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: plan_id
          AttributeType: S
        - AttributeName: repo_name
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: plan_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: repo-timestamp-index
          KeySchema:
            - AttributeName: repo_name
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Service
          Value: cloudops-assistant
        - Key: Feature
          Value: plan-history

Outputs:
  CloudOpsAssistantApi:
    Description: "API Gateway endpoint URL for CloudOps Assistant"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: CloudOpsAssistantApiUrl
      
  TerraformPlansTableName:
    Description: "DynamoDB table for storing terraform plans"
    Value: !Ref TerraformPlansTable
    Export:
      Name: CloudOpsTerraformPlansTable