name: Documentation Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Check README completeness
      run: python scripts/check-readme.py

    - name: Validate architecture diagrams
      run: python scripts/validate-architecture.py

    - name: Check feature architecture coverage
      run: python scripts/check-feature-architecture.py

    - name: Check for broken links
      uses: lycheeverse/lychee-action@v2
      with:
        args: '--verbose --no-progress README.md CONTRIBUTING.md'
        fail: true

    - name: Update badges and progress
      if: github.ref == 'refs/heads/main'
      run: python scripts/update-badges.py
