name: Documentation Checks

on:
  push:
    branches: [ main, develop, Day6 ]
  pull_request:
    branches: [ main, develop ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests

    - name: Check README completeness
      run: python scripts/check-readme.py

    - name: Validate architecture diagrams
      run: python scripts/validate-architecture.py

    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/mlc_config.json'

    - name: Update badges and progress
      if: github.ref == 'refs/heads/main'
      run: python scripts/update-badges.py
